# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-05 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='gps_location',
            field=models.CharField(max_length=30),
        ),
    ]
