# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-05 17:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_auto_20161005_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 10, 5, 17, 48, 56, 360396, tzinfo=utc)),
        ),
    ]
