# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-06 18:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('event_handler', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('-timestamp',)},
        ),
        migrations.AddField(
            model_name='event',
            name='device_id',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
