# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-14 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_handler', '0004_auto_20161007_1742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='battery',
        ),
        migrations.RemoveField(
            model_name='event',
            name='type',
        ),
        migrations.AddField(
            model_name='event',
            name='code',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
