# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-19 07:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device_manager', '0002_auto_20161011_1916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deviceskey',
            name='user',
        ),
        migrations.DeleteModel(
            name='DevicesKey',
        ),
    ]
